import {
  BouquetFilter,
  ChannelGroup,
  ContentCategoryFilter,
  CountryCode,
  EpgBouquetId,
  SatelliteFilter,
} from '../types/epg';

export interface WhitelistedChannelSpec {
  canonicalId: string;
  displayName: string;
  contentCategory?: Exclude<ContentCategoryFilter, 'Tous'>;
  country: Exclude<CountryCode, 'Tous'>;
  satellites: Exclude<SatelliteFilter, 'Tous'>[];
  orbitalPosition: string;
  bouquets: Exclude<BouquetFilter, 'Tous'>[];
  bouquetId?: EpgBouquetId;
  group: Exclude<ChannelGroup, 'Tous'>;
  audioTrackLabel: string;
  subtitleTrackLabel: string;
  lektorStatus?: string;
  hasPolishLektor?: boolean;
  hasSubtitles?: boolean;
  defaultIcon?: string;
}

/**
 * Chaînes Sport / Football autorisées sur Astra 19.2°E, Hotbird 13°E, Hispasat 30°W et Nilesat 7°W :
 * - 4 Grands Championnats : Premier League, LaLiga, Serie A, Bundesliga
 * - Coupes Nationales : FA Cup, Copa del Rey, Coppa Italia, DFB-Pokal
 * - Compétitions UEFA / Internationales : Champions League, Europa League, Conference League, Nations League
 */
export const SPORT_FOOTBALL_WHITELIST: Record<string, WhitelistedChannelSpec> = {
  // 0. ASTRA 19.2°E — ASTRA CANAL+ SPORT / FOOT (FRANCE)
  'canal+.foot.fr': {
    canonicalId: 'CANAL+.Foot.fr',
    displayName: 'Canal+ Foot HD (Astra 19.2°E)',
    contentCategory: 'Sport / Football',
    country: 'FR',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Astra Canal+'],
    bouquetId: 'astra_canal_fr',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio VF / Stadium',
    subtitleTrackLabel: 'UEFA Champions League · Premier League',
    hasSubtitles: true,
  },
  'canal+foot.fr': {
    canonicalId: 'CANAL+.Foot.fr',
    displayName: 'Canal+ Foot HD (Astra 19.2°E)',
    contentCategory: 'Sport / Football',
    country: 'FR',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Astra Canal+'],
    bouquetId: 'astra_canal_fr',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio VF / Stadium',
    subtitleTrackLabel: 'UEFA Champions League · Premier League',
    hasSubtitles: true,
  },
  'canal+.sport.fr': {
    canonicalId: 'CANAL+.Sport.fr',
    displayName: 'Canal+ Sport HD (Astra 19.2°E)',
    contentCategory: 'Sport / Football',
    country: 'FR',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Canal+ France', 'Astra Canal+'],
    bouquetId: 'astra_canal_fr',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio VF / Stadium',
    subtitleTrackLabel: 'UEFA Champions League · Europa · Premier League',
    hasSubtitles: true,
  },
  'canal+sport.fr': {
    canonicalId: 'CANAL+.Sport.fr',
    displayName: 'Canal+ Sport HD (Astra 19.2°E)',
    contentCategory: 'Sport / Football',
    country: 'FR',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Canal+ France', 'Astra Canal+'],
    bouquetId: 'astra_canal_fr',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio VF / Stadium',
    subtitleTrackLabel: 'UEFA Champions League · Europa · Premier League',
    hasSubtitles: true,
  },
  'canal+.sport.360.fr': {
    canonicalId: 'CANAL+.Sport.360.fr',
    displayName: 'Canal+ Sport 360 HD (Astra 19.2°E)',
    contentCategory: 'Sport / Football',
    country: 'FR',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Canal+ France', 'Astra Canal+'],
    bouquetId: 'astra_canal_fr',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio VF / Stadium',
    subtitleTrackLabel: 'Grands Championnats & Coupes d’Europe',
    hasSubtitles: true,
  },
  'canal+sport360.fr': {
    canonicalId: 'CANAL+.Sport.360.fr',
    displayName: 'Canal+ Sport 360 HD (Astra 19.2°E)',
    contentCategory: 'Sport / Football',
    country: 'FR',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Canal+ France', 'Astra Canal+'],
    bouquetId: 'astra_canal_fr',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio VF / Stadium',
    subtitleTrackLabel: 'Grands Championnats & Coupes d’Europe',
    hasSubtitles: true,
  },
  'bein.sports.1.fr': {
    canonicalId: 'beIN.Sports.1.fr',
    displayName: 'beIN Sports 1 HD (Astra Canal+)',
    contentCategory: 'Sport / Football',
    country: 'FR',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Canal+ France', 'Astra Canal+'],
    bouquetId: 'astra_canal_fr',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio VF / Stadium',
    subtitleTrackLabel: 'LaLiga · Bundesliga · FA Cup · Coupe de France',
    hasSubtitles: true,
  },
  'bein.sports.2.fr': {
    canonicalId: 'beIN.Sports.2.fr',
    displayName: 'beIN Sports 2 HD (Astra Canal+)',
    contentCategory: 'Sport / Football',
    country: 'FR',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Canal+ France', 'Astra Canal+'],
    bouquetId: 'astra_canal_fr',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio VF / Stadium',
    subtitleTrackLabel: 'LaLiga · Bundesliga · Serie A · Coupes',
    hasSubtitles: true,
  },
  'bein.sports.3.fr': {
    canonicalId: 'beIN.Sports.3.fr',
    displayName: 'beIN Sports 3 HD (Astra Canal+)',
    contentCategory: 'Sport / Football',
    country: 'FR',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Canal+ France', 'Astra Canal+'],
    bouquetId: 'astra_canal_fr',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio VF / Stadium',
    subtitleTrackLabel: 'Ligue 2 · LaLiga · Bundesliga · Multisports',
    hasSubtitles: true,
  },
  'rmc.sport.1.fr': {
    canonicalId: 'RMC.Sport.1.fr',
    displayName: 'RMC Sport 1 HD (Astra 19.2°E)',
    contentCategory: 'Sport / Football',
    country: 'FR',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Canal+ France', 'Astra Canal+'],
    bouquetId: 'astra_canal_fr',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio VF / Direct',
    subtitleTrackLabel: 'Football & Sports de Combat',
    hasSubtitles: true,
  },
  'dazn.1.fr': {
    canonicalId: 'DAZN.1.fr',
    displayName: 'DAZN 1 HD France (Astra 19.2°E)',
    contentCategory: 'Sport / Football',
    country: 'FR',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Canal+ France', 'Astra Canal+'],
    bouquetId: 'astra_canal_fr',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio VF / Stadium',
    subtitleTrackLabel: 'Ligue 1 McDonald’s · Serie A · Football',
    hasSubtitles: true,
  },
  'eurosport.1.fr': {
    canonicalId: 'Eurosport.1.fr',
    displayName: 'Eurosport 1 HD (Astra Canal+)',
    contentCategory: 'Sport / Football',
    country: 'FR',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Canal+ France', 'Astra Canal+'],
    bouquetId: 'astra_canal_fr',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio VF / Multi-Audio',
    subtitleTrackLabel: 'Coupe de France · Grands Événements Sportifs',
    hasSubtitles: true,
  },
  'eurosport.2.fr': {
    canonicalId: 'Eurosport.2.fr',
    displayName: 'Eurosport 2 HD (Astra Canal+)',
    contentCategory: 'Sport / Football',
    country: 'FR',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Canal+ France', 'Astra Canal+'],
    bouquetId: 'astra_canal_fr',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio VF / Multi-Audio',
    subtitleTrackLabel: 'Football & Multisports Live',
    hasSubtitles: true,
  },
  "l'equipe.fr": {
    canonicalId: 'LEquipe.TNT.fr',
    displayName: "La Chaîne L'Équipe HD (TNT / Astra)",
    contentCategory: 'Sport / Football',
    country: 'FR',
    satellites: ['Astra 19.2°E', 'Hotbird 13°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['TNT France', 'Canal+ France', 'Bis TV (Hotbird 13°E)'],
    bouquetId: 'astra_tnt_fr',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Français (TNT HD)',
    subtitleTrackLabel: 'DVB-Sub FR / Directs Sport & Football',
    hasSubtitles: true,
  },
  'la.chaine.l’équipe.fr': {
    canonicalId: 'LEquipe.TNT.fr',
    displayName: "La Chaîne L'Équipe HD (TNT / Astra)",
    contentCategory: 'Sport / Football',
    country: 'FR',
    satellites: ['Astra 19.2°E', 'Hotbird 13°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['TNT France', 'Canal+ France', 'Bis TV (Hotbird 13°E)'],
    bouquetId: 'astra_tnt_fr',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Français (TNT HD)',
    subtitleTrackLabel: 'DVB-Sub FR / Directs Sport & Football',
    hasSubtitles: true,
  },

  // 1. ASTRA 19.2°E — SKY SPORT DE / DAZN DE
  'sky.sport.premier.league.de': {
    canonicalId: 'Sky.Sport.Premier.League.de',
    displayName: 'Sky Sport Premier League HD (DE)',
    contentCategory: 'Sport / Football',
    country: 'DE',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Sky DE / DAZN DE'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / EN / DE',
    subtitleTrackLabel: 'Premier League · FA Cup',
  },
  'sky.sport.bundesliga.de': {
    canonicalId: 'Sky.Sport.Bundesliga.de',
    displayName: 'Sky Sport Bundesliga HD (DE)',
    contentCategory: 'Sport / Football',
    country: 'DE',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Sky DE / DAZN DE'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: '1. & 2. Bundesliga',
  },
  'sky.sport.bundesliga.1.de': {
    canonicalId: 'Sky.Sport.Bundesliga.1.de',
    displayName: 'Sky Sport Bundesliga 1 HD (DE)',
    contentCategory: 'Sport / Football',
    country: 'DE',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Sky DE / DAZN DE'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Bundesliga Multiplex',
  },
  'sky.sport.bundesliga.2.de': {
    canonicalId: 'Sky.Sport.Bundesliga.2.de',
    displayName: 'Sky Sport Bundesliga 2 HD (DE)',
    contentCategory: 'Sport / Football',
    country: 'DE',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Sky DE / DAZN DE'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Bundesliga Live',
  },
  'sky.sport.bundesliga.uhd.de': {
    canonicalId: 'Sky.Sport.Bundesliga.UHD.de',
    displayName: 'Sky Sport Bundesliga UHD (DE)',
    contentCategory: 'Sport / Football',
    country: 'DE',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Sky DE / DAZN DE'],
    group: 'Sport / Football',
    audioTrackLabel: 'Dolby Atmos / Stadium',
    subtitleTrackLabel: 'Bundesliga 4K UHD',
  },
  'sky.sport.top.event.de': {
    canonicalId: 'Sky.Sport.Top.Event.de',
    displayName: 'Sky Sport Top Event HD (DE)',
    contentCategory: 'Sport / Football',
    country: 'DE',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Sky DE / DAZN DE'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Dual',
    subtitleTrackLabel: 'PL · Bundesliga · DFB-Pokal',
  },
  'sky.sport.mix.de': {
    canonicalId: 'Sky.Sport.Mix.de',
    displayName: 'Sky Sport Mix HD (DE)',
    contentCategory: 'Sport / Football',
    country: 'DE',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Sky DE / DAZN DE'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Dual',
    subtitleTrackLabel: 'FA Cup · Coppa Italia · Coupes',
  },
  'sky.sport.1.de': {
    canonicalId: 'Sky.Sport.1.de',
    displayName: 'Sky Sport 1 HD (DE)',
    contentCategory: 'Sport / Football',
    country: 'DE',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Sky DE / DAZN DE'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'DFB-Pokal · Football Live',
  },
  'sky.sport.2.de': {
    canonicalId: 'Sky.Sport.2.de',
    displayName: 'Sky Sport 2 HD (DE)',
    contentCategory: 'Sport / Football',
    country: 'DE',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Sky DE / DAZN DE'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'DFB-Pokal · Football Live',
  },
  'sky.sport.austria.de': {
    canonicalId: 'Sky.Sport.Austria.de',
    displayName: 'Sky Sport Austria 1 HD (UEFA)',
    contentCategory: 'Sport / Football',
    country: 'DE',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Sky DE / DAZN DE'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'UEFA CL · Europa · Conference',
  },
  'sky.sport.austria.1.hd.de': {
    canonicalId: 'Sky.Sport.Austria.de',
    displayName: 'Sky Sport Austria 1 HD (UEFA)',
    contentCategory: 'Sport / Football',
    country: 'DE',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Sky DE / DAZN DE'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'UEFA CL · Europa · Conference',
  },
  'sky.sport.uhd.de': {
    canonicalId: 'Sky.Sport.UHD.de',
    displayName: 'Sky Sport UHD (DE)',
    contentCategory: 'Sport / Football',
    country: 'DE',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Sky DE / DAZN DE'],
    group: 'Sport / Football',
    audioTrackLabel: 'Dolby Atmos / 4K',
    subtitleTrackLabel: 'Premier League · Bundesliga 4K',
  },
  'dazn.1.de': {
    canonicalId: 'DAZN.1.de',
    displayName: 'DAZN 1 HD (Astra 19.2°E)',
    contentCategory: 'Sport / Football',
    country: 'DE',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Sky DE / DAZN DE'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Live / Stadium',
    subtitleTrackLabel: 'UEFA CL · Bundesliga · LaLiga · Serie A',
  },
  'dazn.2.de': {
    canonicalId: 'DAZN.2.de',
    displayName: 'DAZN 2 HD (Astra 19.2°E)',
    contentCategory: 'Sport / Football',
    country: 'DE',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Sky DE / DAZN DE'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Live / Stadium',
    subtitleTrackLabel: 'UEFA CL · LaLiga · Serie A · FA Cup',
  },
  'dazn.de': {
    canonicalId: 'DAZN.de',
    displayName: 'DAZN Football DE (Astra)',
    contentCategory: 'Sport / Football',
    country: 'DE',
    satellites: ['Astra 19.2°E'],
    orbitalPosition: 'Astra 19.2°E',
    bouquets: ['Sky DE / DAZN DE'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Live / Stadium',
    subtitleTrackLabel: 'UEFA CL · Nations League · Coupes',
  },

  // 2. HISPASAT 30°W / ASTRA 19.2°E — MOVISTAR LALIGA / CAMPEONES / DAZN ES
  'm+.laliga.tv.es': {
    canonicalId: 'M+.LALIGA.TV.es',
    displayName: 'Movistar LaLiga TV HD',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio / Stadium',
    subtitleTrackLabel: 'LaLiga EA Sports · Copa del Rey',
  },
  'm+.laliga.tv.2.es': {
    canonicalId: 'M+.LALIGA.TV.2.es',
    displayName: 'Movistar LaLiga TV 2 HD',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio / Stadium',
    subtitleTrackLabel: 'LaLiga EA Sports · Copa del Rey',
  },
  'm+.laliga.tv.3.es': {
    canonicalId: 'M+.LALIGA.TV.3.es',
    displayName: 'Movistar LaLiga TV 3 HD',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio / Stadium',
    subtitleTrackLabel: 'LaLiga EA Sports',
  },
  'laliga.tv.es': {
    canonicalId: 'LaLiga.TV.es',
    displayName: 'LaLiga TV Bar HD (ES)',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio / Stadium',
    subtitleTrackLabel: 'LaLiga · Football Espagnol',
  },
  'laliga.tv.hypermotion.es': {
    canonicalId: 'LaLiga.TV.Hypermotion.es',
    displayName: 'LaLiga TV Hypermotion HD',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio / Stadium',
    subtitleTrackLabel: 'LaLiga · Copa del Rey',
  },
  'm+.liga.de.campeones.es': {
    canonicalId: 'M+.Liga.de.Campeones.es',
    displayName: 'Movistar Liga de Campeones HD',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio / Stadium',
    subtitleTrackLabel: 'UEFA CL · Europa · Conference League',
  },
  'movistar.liga.de.campeones.es': {
    canonicalId: 'M+.Liga.de.Campeones.es',
    displayName: 'Movistar Liga de Campeones HD',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio / Stadium',
    subtitleTrackLabel: 'UEFA CL · Europa · Conference League',
  },
  'm+.liga.de.campeones2.hdr.es': {
    canonicalId: 'M+.Liga.de.Campeones.2.es',
    displayName: 'Movistar Liga de Campeones 2 HD',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio / Stadium',
    subtitleTrackLabel: 'UEFA CL · Premier League · Bundesliga',
  },
  'movistar.liga.de.campeones.2.es': {
    canonicalId: 'M+.Liga.de.Campeones.2.es',
    displayName: 'Movistar Liga de Campeones 2 HD',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio / Stadium',
    subtitleTrackLabel: 'UEFA CL · Premier League · Bundesliga',
  },
  'movistar.liga.de.campeones.3.es': {
    canonicalId: 'M+.Liga.de.Campeones.3.es',
    displayName: 'Movistar Liga de Campeones 3 HD',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio / Stadium',
    subtitleTrackLabel: 'UEFA Europa & Conference League',
  },
  'movistar.liga.de.campeones.4.es': {
    canonicalId: 'M+.Liga.de.Campeones.4.es',
    displayName: 'Movistar Liga de Campeones 4 HD',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio / Stadium',
    subtitleTrackLabel: 'UEFA Champions & Europa League',
  },
  'dazn.laliga.es': {
    canonicalId: 'DAZN.LaLiga.es',
    displayName: 'DAZN LaLiga HD (ES)',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio / Stadium',
    subtitleTrackLabel: 'LaLiga EA Sports',
  },
  'dazn.laliga.2.es': {
    canonicalId: 'DAZN.LaLiga.2.es',
    displayName: 'DAZN LaLiga 2 HD (ES)',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio / Stadium',
    subtitleTrackLabel: 'LaLiga EA Sports',
  },
  'dazn.1.es': {
    canonicalId: 'DAZN.1.es',
    displayName: 'DAZN 1 HD (ES)',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Live / EN / ES',
    subtitleTrackLabel: 'Premier League · Serie A · FA Cup · Coppa Italia',
  },
  'dazn.1.bar.es': {
    canonicalId: 'DAZN.1.es',
    displayName: 'DAZN 1 HD (ES)',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Live / EN / ES',
    subtitleTrackLabel: 'Premier League · Serie A · FA Cup · Coppa Italia',
  },
  'dazn.2.es': {
    canonicalId: 'DAZN.2.es',
    displayName: 'DAZN 2 HD (ES)',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Live / EN / ES',
    subtitleTrackLabel: 'Premier League · Serie A · Bundesliga',
  },
  'dazn.2.bar.es': {
    canonicalId: 'DAZN.2.es',
    displayName: 'DAZN 2 HD (ES)',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Live / EN / ES',
    subtitleTrackLabel: 'Premier League · Serie A · Bundesliga',
  },
  'dazn.3.es': {
    canonicalId: 'DAZN.3.es',
    displayName: 'DAZN 3 HD (ES)',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Live / EN / ES',
    subtitleTrackLabel: 'Premier League · FA Cup · Coppa Italia',
  },
  'dazn.4.es': {
    canonicalId: 'DAZN.4.es',
    displayName: 'DAZN 4 HD (ES)',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W', 'Astra 19.2°E'],
    orbitalPosition: 'Hispasat 30°W / Astra 19.2°E',
    bouquets: ['Movistar+ / DAZN ES'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Live / EN / ES',
    subtitleTrackLabel: 'Premier League · Serie A · Coupes',
  },

  // 3. HOTBIRD 13°E — SKY SPORT IT / DAZN IT
  'sky.sport.calcio.it': {
    canonicalId: 'Sky.Sport.Calcio.it',
    displayName: 'Sky Sport Calcio HD (IT)',
    contentCategory: 'Sport / Football',
    country: 'IT',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Sky Italia / DAZN IT'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / IT',
    subtitleTrackLabel: 'Serie A · UEFA · Nations League',
  },
  'sky.sport.uno.it': {
    canonicalId: 'Sky.Sport.Uno.it',
    displayName: 'Sky Sport Uno HD (IT)',
    contentCategory: 'Sport / Football',
    country: 'IT',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Sky Italia / DAZN IT'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Dual',
    subtitleTrackLabel: 'UEFA Champions League · Premier League',
  },
  'sky.sport.max.it': {
    canonicalId: 'Sky.Sport.Max.it',
    displayName: 'Sky Sport Max HD (IT)',
    contentCategory: 'Sport / Football',
    country: 'IT',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Sky Italia / DAZN IT'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Dual',
    subtitleTrackLabel: 'Premier League · Bundesliga · UEFA CL',
  },
  'sky.sport.arena.it': {
    canonicalId: 'Sky.Sport.Arena.it',
    displayName: 'Sky Sport Arena HD (IT)',
    contentCategory: 'Sport / Football',
    country: 'IT',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Sky Italia / DAZN IT'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Dual',
    subtitleTrackLabel: 'UEFA Europa & Conference · Nations League',
  },
  'sky.sport.4k.it': {
    canonicalId: 'Sky.Sport.4K.it',
    displayName: 'Sky Sport 4K HDR (IT)',
    contentCategory: 'Sport / Football',
    country: 'IT',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Sky Italia / DAZN IT'],
    group: 'Sport / Football',
    audioTrackLabel: 'Dolby Atmos 4K',
    subtitleTrackLabel: 'Serie A · Premier League · UEFA CL 4K',
  },
  'sky.sport.24.it': {
    canonicalId: 'Sky.Sport.24.it',
    displayName: 'Sky Sport 24 HD (IT)',
    contentCategory: 'Sport / Football',
    country: 'IT',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Sky Italia / DAZN IT'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Live IT',
    subtitleTrackLabel: 'Directs & Multiplex Football',
  },
  'dazn.1.it.it': {
    canonicalId: 'DAZN.1.it',
    displayName: 'DAZN 1 HD (Sky Italia)',
    contentCategory: 'Sport / Football',
    country: 'IT',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Sky Italia / DAZN IT'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / IT',
    subtitleTrackLabel: 'Serie A · LaLiga · FA Cup · Europa League',
  },
  'dazn.2.it.it': {
    canonicalId: 'DAZN.2.it',
    displayName: 'DAZN 2 HD (Sky Italia)',
    contentCategory: 'Sport / Football',
    country: 'IT',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Sky Italia / DAZN IT'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / IT',
    subtitleTrackLabel: 'Serie A · LaLiga · FA Cup',
  },

  // 4. HOTBIRD 13°E — CANAL+ SPORT PL / ELEVEN SPORTS PL
  'canal+.sport.hd.pl': {
    canonicalId: 'CANAL+.Sport.HD.pl',
    displayName: 'Canal+ Sport 1 HD (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'UEFA Champions League · Premier League · LaLiga',
  },
  'canal+.sport.pl': {
    canonicalId: 'CANAL+.Sport.HD.pl',
    displayName: 'Canal+ Sport 1 HD (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'UEFA Champions League · Premier League · LaLiga',
  },
  'canal+.sport.2.hd.pl': {
    canonicalId: 'CANAL+.Sport.2.HD.pl',
    displayName: 'Canal+ Sport 2 HD (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Premier League · LaLiga · UEFA CL',
  },
  'canal+.sport.2.pl': {
    canonicalId: 'CANAL+.Sport.2.HD.pl',
    displayName: 'Canal+ Sport 2 HD (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Premier League · LaLiga · UEFA CL',
  },
  'canal+.sport.3.hd.pl': {
    canonicalId: 'CANAL+.Sport.3.HD.pl',
    displayName: 'Canal+ Sport 3 HD (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Football Live · Championnats',
  },
  'canal+.sport.3.pl': {
    canonicalId: 'CANAL+.Sport.3.HD.pl',
    displayName: 'Canal+ Sport 3 HD (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Football Live · Championnats',
  },
  'canal+.sport.4.hd.pl': {
    canonicalId: 'CANAL+.Sport.4.HD.pl',
    displayName: 'Canal+ Sport 4 HD (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Football Live · Championnats',
  },
  'canal+.sport.4.pl': {
    canonicalId: 'CANAL+.Sport.4.HD.pl',
    displayName: 'Canal+ Sport 4 HD (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Football Live · Championnats',
  },
  'canal+.sport.5.hd.pl': {
    canonicalId: 'CANAL+.Sport.5.HD.pl',
    displayName: 'Canal+ Sport 5 HD (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'LaLiga · UEFA Champions League',
  },
  'canal+.sport.5.pl': {
    canonicalId: 'CANAL+.Sport.5.HD.pl',
    displayName: 'Canal+ Sport 5 HD (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'LaLiga · UEFA Champions League',
  },
  'eleven.sports.1.hd.pl': {
    canonicalId: 'Eleven.Sports.1.HD.pl',
    displayName: 'Eleven Sports 1 HD / 4K (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Serie A · LaLiga · Bundesliga · FA Cup · Coppa Italia',
  },
  'eleven.sports.1.pl': {
    canonicalId: 'Eleven.Sports.1.HD.pl',
    displayName: 'Eleven Sports 1 HD / 4K (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Serie A · LaLiga · Bundesliga · FA Cup · Coppa Italia',
  },
  'eleven.sports.1.4k.pl': {
    canonicalId: 'Eleven.Sports.1.HD.pl',
    displayName: 'Eleven Sports 1 HD / 4K (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Serie A · LaLiga · Bundesliga · FA Cup · Coppa Italia',
  },
  'eleven.sports.2.hd.pl': {
    canonicalId: 'Eleven.Sports.2.HD.pl',
    displayName: 'Eleven Sports 2 HD (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Serie A · LaLiga · Bundesliga · DFB-Pokal',
  },
  'eleven.sports.2.pl': {
    canonicalId: 'Eleven.Sports.2.HD.pl',
    displayName: 'Eleven Sports 2 HD (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Serie A · LaLiga · Bundesliga · DFB-Pokal',
  },
  'eleven.sports.3.hd.pl': {
    canonicalId: 'Eleven.Sports.3.HD.pl',
    displayName: 'Eleven Sports 3 HD (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Serie A · LaLiga · Bundesliga · FA Cup',
  },
  'eleven.sports.3.pl': {
    canonicalId: 'Eleven.Sports.3.HD.pl',
    displayName: 'Eleven Sports 3 HD (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Serie A · LaLiga · Bundesliga · FA Cup',
  },
  'eleven.sports.4.hd.pl': {
    canonicalId: 'Eleven.Sports.4.HD.pl',
    displayName: 'Eleven Sports 4 HD (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Serie A · Bundesliga · Coupes Nationales',
  },
  'eleven.sports.4.pl': {
    canonicalId: 'Eleven.Sports.4.HD.pl',
    displayName: 'Eleven Sports 4 HD (PL)',
    contentCategory: 'Sport / Football',
    country: 'PL',
    satellites: ['Hotbird 13°E'],
    orbitalPosition: 'Hotbird 13°E',
    bouquets: ['Canal+ / Eleven / FilmBox'],
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / Live',
    subtitleTrackLabel: 'Serie A · Bundesliga · Coupes Nationales',
  },

  // 5. BADR / ES'HAILSAT 26°E — BEIN SPORTS MENA / SSC SPORTS / AL KASS / AD SPORTS
  'bein_sports1_digital_mono_en.bein': {
    canonicalId: 'beIN.Sports.1.badr',
    displayName: "beIN Sports 1 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'Premier League · LaLiga · UEFA CL · Nations League',
  },
  'bein_sports1_digital_mono_ar.bein': {
    canonicalId: 'beIN.Sports.1.badr',
    displayName: "beIN Sports 1 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'Premier League · LaLiga · UEFA CL · Nations League',
  },
  'bein.sports.hd.ae': {
    canonicalId: 'beIN.Sports.1.badr',
    displayName: "beIN Sports 1 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'Premier League · LaLiga · UEFA CL · Nations League',
  },
  'bein_sports2_digital_mono_en.bein': {
    canonicalId: 'beIN.Sports.2.badr',
    displayName: "beIN Sports 2 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'Premier League · UEFA Champions League · FA Cup',
  },
  'bein_sports2_digital_mono_ar.bein': {
    canonicalId: 'beIN.Sports.2.badr',
    displayName: "beIN Sports 2 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'Premier League · UEFA Champions League · FA Cup',
  },
  'bein_sports3_digital_mono_en.bein': {
    canonicalId: 'beIN.Sports.3.badr',
    displayName: "beIN Sports 3 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'LaLiga · UEFA Champions League · Europa League',
  },
  'bein_sports3_digital_mono_ar.bein': {
    canonicalId: 'beIN.Sports.3.badr',
    displayName: "beIN Sports 3 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'LaLiga · UEFA Champions League · Europa League',
  },
  'bein_sports4_digital_mono_en.bein': {
    canonicalId: 'beIN.Sports.4.badr',
    displayName: "beIN Sports 4 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'Bundesliga · UEFA Europa & Conference League',
  },
  'bein_sports4_digital_mono_ar.bein': {
    canonicalId: 'beIN.Sports.4.badr',
    displayName: "beIN Sports 4 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'Bundesliga · UEFA Europa & Conference League',
  },
  'bein_sports5_digital_mono_en.bein': {
    canonicalId: 'beIN.Sports.5.badr',
    displayName: "beIN Sports 5 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'Bundesliga · FA Cup · UEFA Compétitions',
  },
  'bein_sports5_digital_mono_ar.bein': {
    canonicalId: 'beIN.Sports.5.badr',
    displayName: "beIN Sports 5 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'Bundesliga · FA Cup · UEFA Compétitions',
  },
  'bein_sports66_digital_mono-01_en.bein': {
    canonicalId: 'beIN.Sports.6.badr',
    displayName: "beIN Sports 6 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'UEFA Europa & Conference · Nations League',
  },
  'bein_sports1_english_digital_mono_en.bein': {
    canonicalId: 'beIN.Sports.English.1.badr',
    displayName: "beIN Sports 1 English HD (Badr 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'VO Anglais (Commentaires EN)',
    subtitleTrackLabel: 'Premier League · UEFA CL · LaLiga',
  },
  'bein_sports2_english_digital_mono_en.bein': {
    canonicalId: 'beIN.Sports.English.2.badr',
    displayName: "beIN Sports 2 English HD (Badr 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'VO Anglais (Commentaires EN)',
    subtitleTrackLabel: 'Premier League · UEFA CL · FA Cup',
  },
  'bein_sports1_french_digital_mono_en.bein': {
    canonicalId: 'beIN.Sports.French.1.badr',
    displayName: "beIN Sports 1 French HD (Badr 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Français (VF)',
    subtitleTrackLabel: 'UEFA CL · LaLiga · Premier League · Bundesliga',
  },
  'bein_sports2_french_digital_mono_en.bein': {
    canonicalId: 'beIN.Sports.French.2.badr',
    displayName: "beIN Sports 2 French HD (Badr 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Français (VF)',
    subtitleTrackLabel: 'UEFA Europa League · Coupes Nationales',
  },
  'bein_sports_max1_digital_mono_en.bein': {
    canonicalId: 'beIN.Sports.Max.1.badr',
    displayName: "beIN Sports Max 1 HD (Badr 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN / FR',
    subtitleTrackLabel: 'UEFA Nations League · Euro · Grands Tournois',
  },
  'bein_sports_max2_digital_mono_en.bein': {
    canonicalId: 'beIN.Sports.Max.2.badr',
    displayName: "beIN Sports Max 2 HD (Badr 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN / FR',
    subtitleTrackLabel: 'UEFA Nations League · Compétitions Internationales',
  },
  'bein_sports_xtra1_digital_mono_en.bein': {
    canonicalId: 'beIN.Sports.Xtra.1.badr',
    displayName: "beIN Sports Xtra 1 HD (Badr 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'Premier League · LaLiga · Bundesliga Multiplex',
  },
  'bein_sports_xtra2_digital_mono_en.bein': {
    canonicalId: 'beIN.Sports.Xtra.2.badr',
    displayName: "beIN Sports Xtra 2 HD (Badr 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'Premier League · LaLiga · Bundesliga Multiplex',
  },
  'alkass_1_ar.bein': {
    canonicalId: 'AlKass.1.badr',
    displayName: "Al Kass 1 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'AFC Champions League · Coupes & Football MENA',
  },
  'alkass_1_en.bein': {
    canonicalId: 'AlKass.1.badr',
    displayName: "Al Kass 1 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'AFC Champions League · Coupes & Football MENA',
  },
  'alkass_2_ar.bein': {
    canonicalId: 'AlKass.2.badr',
    displayName: "Al Kass 2 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'AFC Champions League · Football Live',
  },
  'alkass_2_en.bein': {
    canonicalId: 'AlKass.2.badr',
    displayName: "Al Kass 2 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'AFC Champions League · Football Live',
  },
  'alkass_3_ar.bein': {
    canonicalId: 'AlKass.3.badr',
    displayName: "Al Kass 3 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'Football International & Championnats',
  },
  'alkass_3_en.bein': {
    canonicalId: 'AlKass.3.badr',
    displayName: "Al Kass 3 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'Football International & Championnats',
  },
  'alkass_4_ar.bein': {
    canonicalId: 'AlKass.4.badr',
    displayName: "Al Kass 4 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'Football International & Coupes',
  },
  'alkass_4_en.bein': {
    canonicalId: 'AlKass.4.badr',
    displayName: "Al Kass 4 HD (Badr / Es'hailSat 26°E)",
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio AR / EN',
    subtitleTrackLabel: 'Football International & Coupes',
  },
  'en:.ssc1.hd.sa': {
    canonicalId: 'SSC.1.HD.badr',
    displayName: 'SSC 1 HD (Badr 26°E)',
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio EN / AR',
    subtitleTrackLabel: 'Roshn Saudi League · Copa del Rey · AFC CL',
  },
  'en:.ssc2.hd.sa': {
    canonicalId: 'SSC.2.HD.badr',
    displayName: 'SSC 2 HD (Badr 26°E)',
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio EN / AR',
    subtitleTrackLabel: 'Roshn Saudi League · Copa del Rey · Coupes',
  },
  'en:.ssc3.hd.sa': {
    canonicalId: 'SSC.3.HD.badr',
    displayName: 'SSC 3 HD (Badr 26°E)',
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio EN / AR',
    subtitleTrackLabel: 'Football International & Coupes',
  },
  'en:.ssc4.hd.sa': {
    canonicalId: 'SSC.4.HD.badr',
    displayName: 'SSC 4 HD (Badr 26°E)',
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio EN / AR',
    subtitleTrackLabel: 'Football International & Coupes',
  },
  'en:.ssc5.hd.sa': {
    canonicalId: 'SSC.5.HD.badr',
    displayName: 'SSC 5 HD (Badr 26°E)',
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio EN / AR',
    subtitleTrackLabel: 'Football International & Coupes',
  },
  'en:.ssc.extra.1.hd.sa': {
    canonicalId: 'SSC.Extra.1.HD.badr',
    displayName: 'SSC Extra 1 HD (Badr 26°E)',
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio EN / AR',
    subtitleTrackLabel: 'Multiplex Football & Coupes',
  },
  'en:.ssc.extra.2.hd.sa': {
    canonicalId: 'SSC.Extra.2.HD.badr',
    displayName: 'SSC Extra 2 HD (Badr 26°E)',
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio EN / AR',
    subtitleTrackLabel: 'Multiplex Football & Coupes',
  },
  'ad.sports.1.hd.ae': {
    canonicalId: 'AD.Sports.1.HD.badr',
    displayName: 'AD Sports 1 HD (Badr 26°E)',
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio EN / AR',
    subtitleTrackLabel: 'Serie A · Coppa Italia · Football International',
  },
  'en:.abu.dhabi.sports.1.ae': {
    canonicalId: 'AD.Sports.1.HD.badr',
    displayName: 'AD Sports 1 HD (Badr 26°E)',
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio EN / AR',
    subtitleTrackLabel: 'Serie A · Coppa Italia · Football International',
  },
  'ad.sports.2.hd.ae': {
    canonicalId: 'AD.Sports.2.HD.badr',
    displayName: 'AD Sports 2 HD (Badr 26°E)',
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio EN / AR',
    subtitleTrackLabel: 'Serie A · Coppa Italia · Football International',
  },
  'en:.abu.dhabi.sports.2.ae': {
    canonicalId: 'AD.Sports.2.HD.badr',
    displayName: 'AD Sports 2 HD (Badr 26°E)',
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio EN / AR',
    subtitleTrackLabel: 'Serie A · Coppa Italia · Football International',
  },
  'en:.ad.sports.extra.ae': {
    canonicalId: 'AD.Sports.Extra.HD.badr',
    displayName: 'AD Sports Extra HD (Badr 26°E)',
    contentCategory: 'Sport / Football',
    country: 'AR',
    satellites: ["Badr / Es'hailSat 26°E"],
    orbitalPosition: "Badr / Es'hailSat 26°E",
    bouquets: ['Badr 26°E (beIN / SSC / Al Kass)', 'beIN / SSC / AD Sports'],
    bouquetId: 'badr_bein_ssc',
    group: 'Sport / Football',
    audioTrackLabel: 'Multi-Audio EN / AR',
    subtitleTrackLabel: 'Serie A · Coppa Italia · Football Live',
  },
  'sport.tv1.hd.pt': {
    canonicalId: 'Sport.TV1.HD.pt',
    displayName: 'Sport TV 1 HD (Hispasat 30°W)',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W'],
    orbitalPosition: 'Hispasat 30°W',
    bouquets: ['MEO / NOS / Movistar (30°W)'],
    bouquetId: 'hispasat_meo_nos',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / PT / EN',
    subtitleTrackLabel: 'Liga Portugal · UEFA Champions League · Premier League',
  },
  'sport.tv2.hd.pt': {
    canonicalId: 'Sport.TV2.HD.pt',
    displayName: 'Sport TV 2 HD (Hispasat 30°W)',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W'],
    orbitalPosition: 'Hispasat 30°W',
    bouquets: ['MEO / NOS / Movistar (30°W)'],
    bouquetId: 'hispasat_meo_nos',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / PT / EN',
    subtitleTrackLabel: 'Premier League · Serie A · Taça de Portugal',
  },
  'sport.tv3.hd.pt': {
    canonicalId: 'Sport.TV3.HD.pt',
    displayName: 'Sport TV 3 HD (Hispasat 30°W)',
    contentCategory: 'Sport / Football',
    country: 'ES',
    satellites: ['Hispasat 30°W'],
    orbitalPosition: 'Hispasat 30°W',
    bouquets: ['MEO / NOS / Movistar (30°W)'],
    bouquetId: 'hispasat_meo_nos',
    group: 'Sport / Football',
    audioTrackLabel: 'Audio Stadium / PT / EN',
    subtitleTrackLabel: 'UEFA Europa & Conference League · Football',
  },
};

const SYNC_TRANSLATION_RULES: Array<[RegExp, string]> = [
  // Compétitions de football (PL, ES, DE, IT, EN -> FR)
  [/\bLiga angielska\b/gi, 'Premier League'],
  [/\bLiga hiszpańska\b/gi, 'LaLiga'],
  [/\bLiga włoska\b/gi, 'Serie A'],
  [/\bLiga niemiecka\b/gi, 'Bundesliga'],
  [/\bLiga francuska\b/gi, 'Ligue 1'],
  [/\bLiga Mistrzów UEFA\b/gi, 'UEFA Champions League'],
  [/\bLiga Mistrzów\b/gi, 'UEFA Champions League'],
  [/\bLiga Europy UEFA\b/gi, 'UEFA Europa League'],
  [/\bLiga Konferencji UEFA\b/gi, 'UEFA Conference League'],
  [/\bLiga Narodów UEFA\b/gi, 'Ligue des Nations UEFA'],
  [/\bUEFA Nations League\b/gi, 'Ligue des Nations UEFA'],
  [/\bPuchar Anglii\b/gi, "Coupe d'Angleterre (FA Cup)"],
  [/\bPuchar Króla\b/gi, 'Coupe du Roi (Copa del Rey)'],
  [/\bPuchar Włoch\b/gi, "Coupe d'Italie (Coppa Italia)"],
  [/\bPuchar Niemiec\b/gi, "Coupe d'Allemagne (DFB-Pokal)"],
  [/\bPiłka nożna\b/gi, 'Football'],
  [/\bmecz:\s*/gi, 'Match : '],
  [/\bmecz\b/gi, 'Match'],
  [/(\d+)\.\s*kolejka/gi, '$1e journée'],
  [/(\d+)\.\s*Spieltag/gi, '$1e journée'],
  [/\bJornada\s+(\d+)/gi, 'Journée $1'],
  [/(\d+)a\s+Giornata/gi, '$1e journée'],
  [/\bResúmenes\b/gi, 'Résumés'],
  [/\bResumen\b/gi, 'Résumé'],
  [/\bSintesi\b/gi, 'Résumé'],
  [/\bSkróty\b/gi, 'Résumés'],
  [/\bKonferenz\b/gi, 'Multiplex'],
  [/\bAlle Spiele,\s*alle Tore\b/gi, 'Tous les matchs, tous les buts'],
  [/\bOctavos de final\b/gi, 'Huitièmes de finale'],
  [/\bCuartos de final\b/gi, 'Quarts de finale'],
  [/\bOttavi di finale\b/gi, 'Huitièmes de finale'],
  [/\bQuarti di finale\b/gi, 'Quarts de finale'],
  [/\bViertelfinale\b/gi, 'Quarts de finale'],
  [/\bHalbfinale\b/gi, 'Demi-finale'],
  [/\bAchtelfinale\b/gi, 'Huitièmes de finale'],
  [/\bSemifinal(?:e|es)?\b/gi, 'Demi-finale'],
  [/\bMini Matche?s?\b/gi, 'Mini-Match (Résumé étendu)'],
  [/\bHighlights\b/gi, 'Temps forts & Résumés'],
  [/\bAfrica Cup of Nations\s*\(?\s*AFCON\s*\)?\s*Qualification\b/gi, 'Qualifications CAN'],
  // Clubs & Pays fréquents dans les titres EPG PL/ES/IT/DE/EN
  [/\bReal Madryt\b/gi, 'Real Madrid'],
  [/\bFC Barcelona\b/gi, 'FC Barcelone'],
  [/\bInter Mediolan\b/gi, 'Inter Milan'],
  [/\bAC Mediolan\b/gi, 'AC Milan'],
  [/\bAS Roma\b/gi, 'AS Rome'],
  [/\bRB Lipsk\b/gi, 'RB Leipzig'],
  [/\bBayern Monachium\b/gi, 'Bayern Munich'],
  [/\bBrujas\b/gi, 'Club Bruges'],
  [/\bNápoles\b/gi, 'Naples'],
  [/\bCechia\b/gi, 'Tchéquie'],
  [/\bCroazia\b/gi, 'Croatie'],
  [/\bSpagna\b/gi, 'Espagne'],
  [/\bInghilterra\b/gi, 'Angleterre'],
  [/\bGermania\b/gi, 'Allemagne'],
  [/\bFrancia\b/gi, 'France'],
  [/\bPortogallo\b/gi, 'Portugal'],
  [/\bOlanda\b/gi, 'Pays-Bas'],
  [/\bBelgio\b/gi, 'Belgique'],
  [/\bNorway\b/gi, 'Norvège'],
  [/\bWales\b/gi, 'Pays de Galles'],
  [/\bEgypt\b/gi, 'Égypte'],
  [/\bMorocco\b/gi, 'Maroc'],
  [/\bEngland\b/gi, 'Angleterre'],
  [/\bSpain\b/gi, 'Espagne'],
  [/\bGermany\b/gi, 'Allemagne'],
  [/\bItaly\b/gi, 'Italie'],
  [/\bNetherlands\b/gi, 'Pays-Bas'],
  [/\bBelgium\b/gi, 'Belgique'],
];

/**
 * Traduit instantanément les intitulés et sous-titres EPG étrangers (notamment Football/Sport
 * et mentions de saisons/épisodes) en français dès le parsing XML.
 */
export function translateEpgTextToFrenchSync(text?: string): string {
  if (!text) return '';
  let out = text.trim();
  for (const [pattern, replacement] of SYNC_TRANSLATION_RULES) {
    out = out.replace(pattern, replacement);
  }
  return out;
}
